### ISSUE TITLE
Windows version on binstar.org/scopatz doesn't work

### ISSUE THREAD

**Issue by melund** [scopatz/xonsh#278]
The windows version of xonsh on binstar.org/scopatz doesn't work. 

The package has its file in a file structure that doesn't work on windows: 
`\lib\python3.4\site-packages\xonsh\`

should have been: 
`\lib\site-packages\xonsh\`

Were it maybe created with `conda convert` on a package built for linux or mac? Maybe it is a bug in conda convert. 

Anyway, when I built the conda recipe on windows the package works fine. If anyone want to try:
`conda install -c melund xonsh`

I made some small changes to the build recipe. For example, I have never gotten the build script inside `meta.yaml` to work on windows. So I had to add a `bld.bat` containing "python setup.py install" next to `meta.yaml`. 

My `meta.yaml` looks like this now: 
``` yaml
package:
  name: xonsh
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: ../

build:            # (optional)
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install
  entry_points:
    - xonsh = xonsh.main:main
  
  
requirements:
  build:
    - python >=3.4
    - ply
  run:
    - python >=3.4
    - ply

about:
  home: http://xonsh.org/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-compatible shell.

app:
  entry: xonsh
  icon: ../docs/_static/ascii_conch_part_color.png
```

**Comment by scopatz** [comment]
> Were it maybe created with conda convert on a package built for linux or mac? Maybe it is a bug in conda convert.

This was made with conda convert and other people have reported the error too. It would be super helpful if you could do a few things: 

1. report this issue on the conda list.  I haven't found the time to do this :(.
2. Open up a Pull Request so that we can test your meta.yml changes, 
3. Push your working windows package up to binstar (maybe it is already?) and then I can copy it into the official location.

Any or all of these would be great! Thanks!

**Comment by melund** [comment]
I made a pull request: https://github.com/scopatz/xonsh/pull/279

The windows packages I build are on binstar.org/melund/xonsh 

Bare in mind that they are build from the newest version in the git repository. The version says 0.1.6.-36. The build number indicate they are 36 commits ahead of 0.1.6...

**Comment by melund** [comment]
I have made a pull request for the broken "conda convert" (from linux to windows). 
https://github.com/conda/conda-build/pull/481

The problem arise when there is no hard version dependency in the conda recipe. So a work-around until they update conda build, is to remove the (>=) in the recipe. 

``` yaml
requirements:
  build:
    - python 3.4
    - ply
  run:
    - python 3.4
    - ply
```
/Morten
